version: "3"

services:  # Corrected from 'service'
  api:
    build: .  # Specify build context

    ports:
      - "8000:8000"
    volumes:
      - C:/Users/RONAK/OneDrive/Desktop/Drona\ Foundation/Fast\ Api\ Learning:/usr/src/app
  # Fixed path issue
    environment:
      - DATABASE_HOSTNAME=ronak
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=fastapi
      - SECRET_KEY=5b9876f11bc4d834aab2d93b440f9e7cf6f5795109d739f99bb9ebfefc7de303
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    # command: uvicorn app.main:app --reload --host 0.0.0.0

    depends_on:
      - ronak
  ronak:
    image: postgres  
    environment:
      - POSTGRES_PASSWORD=admin  # Removed space around '='
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
