"""update database

Revision ID: 26cfd35afa93
Revises: aacd45a1666b
Create Date: 2025-02-10 12:32:20.473496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cfd35afa93'
down_revision: Union[str, None] = 'aacd45a1666b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), server_default=sa.text('1010101010'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
