name : Build and Deploy Code

on: [push,pull_request]
  
jobs: 
  job1: 
    env: 
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_NAME: fastapi
      SECRET_KEY: 5b9876f11bc4d834aab2d93b440f9e7cf6f5795109d739f99bb9ebfefc7de303
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30




    runs-on: ubuntu-latest
    steps: 
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.12
        uses: actions/setup-python@v2
        with: 
          python-version: "3.12"
      - name: update pip
        run:  python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest


